### ISSUE TITLE
Rake file support

### ISSUE THREAD

**Issue by maartenvg** [volmer/policial#21]
I'd like to add rake files to be included in Shopify's Policial checks. We can do that either by updating Policial [here](https://github.com/volmer/policial/blob/master/lib/policial/style_guides/ruby.rb#L26) or by adding `**/*.rake` to the `AllCops` section of `.rubocop.yml` in the ruby style guide repo. 

@volmer what has your preference? Should Policial be opinionated about what constitutes a ruby file, or is this something you'd rather have configuration deal with. I prefer the latter option.

**Comment by volmer** [comment]
RuboCop inspects [all `*.rake` files by default](https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L15) so I think Policial should do the same. And that seems to be the case already, no? https://github.com/volmer/policial/commit/8e890f3809a5aceff65ac31d075de86cb9358710

**Comment by maartenvg** [comment]
Apparently not: https://github.com/Shopify/shopify/pull/100348

Locally running rubocop against that file it finds the line too long, but Policial ignores it.

**Comment by volmer** [comment]
Ok, I have some ideas of what could be wrong. I'll keep you posted!

**Comment by volmer** [comment]
Ok, found the problem: Policial was treating RuboCop's `Include` config as a Regex, while it is actually just another pattern to match filepaths. So `lib/task.rake` would never match `**/*.rake`. 

I fixed it by replacing the Regex matching with a direct call to  RuboCop's API: https://github.com/volmer/policial/commit/fd295d97f3099abe66901de76122115f5145a45a#diff-09799febb1bac30fc7a20da200ada273L25

Everything should work fine now but please let me know if the issue persists.

**Comment by maartenvg** [comment]
Thanks @volmer
