### ISSUE TITLE
Need to support pushes too

### ISSUE THREAD

**Issue by arthurnn** [volmer/policial#6]
policial.io will need to support pull_request hooks and also pushes. So we can generate things like badges.

**Comment by arthurnn** [comment]
Not sure how we are going to do this. I think we will have to clone the entire repo, using a sha, and run the command in all files.
Does that make sense?

**Comment by volmer** [comment]
To inspect the entire repo linters can be enabled on a CI server directly. Policial will remain responsible for pull requests only for now.
